// --- runtime exports (schemas, functions, classes) ---
export { healthResponseSchema, readyResponseSchema } from "./health";
export {
  channelManifestEntrySchema,
  channelManifestSchema,
  eventLocationSchema,
  eventTypeSchema,
  geoStructureSchema,
  ingestEnvelopeSchema,
  locationPrecisionSchema,
  macroZoneSchema,
  parseConfigSchema,
  parseCursorSchema,
  parsedEventSchema,
  rawMessageSchema,
  rawMessageTelegramExtensionSchema,
  severitySchema,
  ingestAdapterKindSchema,
  providerStatusSchema,
  ingestModeSchema,
  sourceKindSchema,
  bindingModeSchema,
  backfillStrategySchema,
  backfillJobStatusSchema,
  credentialRefsSchema,
  adapterConfigSchema,
  ingestBindingRecordSchema,
  ingestProviderRecordSchema,
  createIngestProviderSchema,
  updateIngestProviderSchema,
  createIngestBindingSchema,
  telegramAdapterConfigSchema,
  mtproxyTransportSchema,
  manualIngestRequestSchema,
  manualIngestResponseSchema,
  timelineOrderingKeySchema,
  timelineAnchorSchema,
  timelineQuerySchema,
  createBackfillJobSchema,
  backfillJobRecordSchema,
  timelineResponseSchema,
  fetchHistoryBatchSchema,
  ingestManifestEntrySchema,
  ingestManifestSchema,
  sessionKindSchema,
  sessionArtifactSchema,
  sessionDeployRequestSchema,
  sessionProbeResultSchema,
} from "./ingest";
export {
  getActiveEventsQuerySchema,
  getEventsByRegionQuerySchema,
  getGeoSyncHistoryQuerySchema,
  getParseAttemptsQuerySchema,
  getRegionGeometryQuerySchema,
  syncAllCommandSchema,
  syncPlacesCommandSchema,
  syncRegionsCommandSchema,
} from "./cqrs";
export { domainEventSchema, domainEventTypeSchema } from "./events";
export {
  placeStatusActionSchema,
  placeStatusEventSchema,
} from "./events";
export {
  aliasDraftSchema,
  geoEnrichmentArtifactSchema,
  geoEnrichmentCatalogSchema,
  geoEnrichmentDadataSchema,
  geoEnrichmentFinalizerSchema,
  geoEnrichmentLlmSchema,
  geoEnrichmentNominatimSchema,
  geoPipelineReportSchema,
  geoPipelineStepLogSchema,
  placeDraftSchema,
  regionDraftSchema,
  statusDictionaryEntrySchema,
  statusDictionarySchema,
  stateLevelSchema,
  STATE_LEVEL_RANK,
  regionStateRecordSchema,
  regionStateEventSchema,
  layoutTileSchema,
  mapRegionSnapshotSchema,
  mapSnapshotSchema,
  regionAdjacencySchema,
  warningSchema,
} from "./geo";
export {
  wsChannelSchema,
  wsClientMessageSchema,
  wsServerMessageSchema,
} from "./realtime";
export {
  parseReportClassificationSchema,
  parseReportEnrichSchema,
  parseReportEventSchema,
  parseReportGeoSchema,
  parseReportSchema,
} from "./reports";

// --- type-only exports ---
export type { HealthResponse, ReadyResponse } from "./health";
export type {
  ChannelManifest,
  ChannelManifestEntry,
  EventLocation,
  EventType,
  GeoStructure,
  IngestEnvelope,
  LocationPrecision,
  MacroZone,
  ParseConfig,
  ParseCursor,
  ParsedEvent,
  RawMessage,
  RawMessageTelegramExtension,
  Severity,
  IngestAdapterKind,
  ProviderStatus,
  IngestMode,
  SourceKind,
  BindingMode,
  BackfillStrategy,
  BackfillJobStatus,
  CredentialRefs,
  IngestBindingRecord,
  IngestProviderRecord,
  CreateIngestProvider,
  UpdateIngestProvider,
  CreateIngestBinding,
  TelegramAdapterConfig,
  MtproxyTransport,
  ManualIngestRequest,
  ManualIngestResponse,
  TimelineOrderingKey,
  TimelineAnchor,
  TimelineQuery,
  CreateBackfillJob,
  BackfillJobRecord,
  TimelineResponse,
  IngestManifestEntry,
  IngestManifest,
  SessionKind,
  SessionArtifact,
  SessionDeployRequest,
  SessionProbeResult,
  SessionMaterial,
  SessionWriteInput,
} from "./ingest";
export type {
  GetActiveEventsQuery,
  GetEventsByRegionQuery,
  GetGeoSyncHistoryQuery,
  GetParseAttemptsQuery,
  GetRegionGeometryQuery,
  SyncAllCommand,
  SyncPlacesCommand,
  SyncRegionsCommand,
} from "./cqrs";
export type {
  DomainEvent,
  DomainEventType,
  PlaceStatusAction,
  PlaceStatusEvent,
} from "./events";
export type {
  AliasDraft,
  GeoEnrichmentArtifact,
  GeoEnrichmentCatalog,
  GeoEnrichmentDadata,
  GeoEnrichmentFinalizer,
  GeoEnrichmentLlm,
  GeoEnrichmentNominatim,
  GeoNode,
  GeoPipelineReport,
  PlaceDraft,
  RegionDraft,
  StatusDictionary,
  StatusDictionaryEntry,
  StateLevel,
  RegionStateRecord,
  RegionStateEvent,
  LayoutTile,
  MapRegionSnapshot,
  MapSnapshot,
  RegionAdjacency,
  Warning,
} from "./geo";
export type {
  WsChannel,
  WsClientMessage,
  WsServerMessage,
} from "./realtime";
export type {
  ParseReport,
  ParseReportClassification,
  ParseReportEnrich,
  ParseReportEvent,
  ParseReportGeo,
  ParseReportGeoPipeline,
} from "./reports";

