// --- runtime exports (schemas, functions, classes) ---
export { healthResponseSchema, readyResponseSchema } from "./health";
export {
  processMetricsSchema,
  workerProbeStatusSchema,
  workerStatusResponseSchema,
} from "./worker-status";
export type {
  ProcessMetrics,
  WorkerProbeStatus,
  WorkerStatusResponse,
} from "./worker-status";
export {
  channelManifestEntrySchema,
  channelManifestSchema,
  eventLocationSchema,
  eventSubjectSchema,
  eventTypeSchema,
  pvoStatsSchema,
  geoStructureSchema,
  ingestEnvelopeSchema,
  locationPrecisionSchema,
  macroZoneSchema,
  parseConfigSchema,
  parseCursorSchema,
  parsedEventSchema,
  rawMessageSchema,
  rawMessageTelegramExtensionSchema,
  severitySchema,
  ingestAdapterKindSchema,
  providerStatusSchema,
  ingestModeSchema,
  sourceKindSchema,
  bindingModeSchema,
  backfillStrategySchema,
  backfillJobStatusSchema,
  credentialRefsSchema,
  adapterConfigSchema,
  ingestBindingRecordSchema,
  ingestProviderRecordSchema,
  createIngestProviderSchema,
  updateIngestProviderSchema,
  createIngestBindingSchema,
  telegramAdapterConfigSchema,
  mtproxyTransportSchema,
  manualIngestRequestSchema,
  manualIngestResponseSchema,
  timelineOrderingKeySchema,
  timelineAnchorSchema,
  timelineQuerySchema,
  createBackfillJobSchema,
  backfillJobRecordSchema,
  timelineResponseSchema,
  fetchHistoryBatchSchema,
  messageFeedItemSchema,
  messageFeedResponseSchema,
  stateChangeEventItemSchema,
  stateChangeEventsResponseSchema,
  ingestManifestEntrySchema,
  ingestManifestSchema,
  sessionKindSchema,
  sessionArtifactSchema,
  sessionDeployRequestSchema,
  sessionProbeResultSchema,
  ingestConnectionPhaseSchema,
  ingestProviderConnectionSnapshotSchema,
} from "./ingest";
export {
  getActiveEventsQuerySchema,
  getEventsByRegionQuerySchema,
  getGeoSyncHistoryQuerySchema,
  getParseAttemptsQuerySchema,
  getRegionGeometryQuerySchema,
  syncAllCommandSchema,
  syncPlacesCommandSchema,
  syncRegionsCommandSchema,
} from "./cqrs";
export { domainEventSchema, domainEventTypeSchema } from "./events";
export {
  placeStatusActionSchema,
  placeStatusEventSchema,
} from "./events";
export {
  aliasDraftSchema,
  geoEnrichmentArtifactSchema,
  geoEnrichmentStateSchema,
  geoEnrichmentCatalogSchema,
  geoEnrichmentDadataSchema,
  geoEnrichmentFinalizerSchema,
  geoEnrichmentLlmSchema,
  geoEnrichmentNominatimSchema,
  geoEventCategorySchema,
  geoPipelineReportSchema,
  geoPipelineStepLogSchema,
  placeDraftSchema,
  regionDraftSchema,
  statusDictionaryEntrySchema,
  statusDictionarySchema,
  stateLevelSchema,
  STATE_LEVEL_RANK,
  regionStateRecordSchema,
  regionStateEventSchema,
  layoutTileSchema,
  mapRegionSnapshotSchema,
  mapPlaceSnapshotSchema,
  mapVicinityScopeSnapshotSchema,
  placeStateEventSchema,
  mapSnapshotSchema,
  mapRegionsStateResponseSchema,
  mapPlacesStateResponseSchema,
  regionAdjacencySchema,
  warningSchema,
  sourceMessageSchema,
  sourceMessageResponseSchema,
} from "./geo";
export {
  enrichmentSourceSchema,
  mergePrecisionSchema,
  provenanceMetaSchema,
  fieldProvenance,
  SOURCE_TRUST,
  PRECISION_RANK,
  enricherIdSchema,
  phaseTriggerSchema,
  phaseTriggerModeSchema,
  legacyTriggerToMode,
  phaseScopeSchema,
  phaseKindSchema,
  enrichStageSchema,
  phasePolicySchema,
  DEFAULT_PHASE_POLICY,
  phaseManifestEntrySchema,
  phaseManifestSchema,
  phaseDefinitionSchema,
  manualRunScopeSchema,
  LEGACY_PHASE_ID_MAP,
  normalizePhaseManifestEntry,
  phaseRunStatusSchema,
  phaseRunControlSchema,
  phaseRunLogEntrySchema,
  phaseRunStatsSchema,
  phaseRunSchema,
  phaseReplayRequestSchema,
  phaseRunsOverviewSchema,
} from "./enrichment";
export {
  wsChannelSchema,
  wsClientMessageSchema,
  wsServerMessageSchema,
} from "./realtime";
export {
  attachRuleSchema,
  eventCandidateAnchorSchema,
  eventCandidateSchema,
  finalizeContextSchema,
  finalizeModeSchema,
  finalizeResultSchema,
  messageBlockKindSchema,
  messageBlockSchema,
  messageParseWorkspaceStatusSchema,
  parseWorkspaceSchema,
  traitAttachmentSchema,
} from "./parse";
export {
  parseReportClassificationSchema,
  parseReportEnrichSchema,
  parseReportEventSchema,
  parseReportGeoSchema,
  parseReportSchema,
} from "./reports";
export {
  backfillJobProgressSchema,
  backfillJobListItemSchema,
  backfillJobsQuerySchema,
  channelAdminItemSchema,
  channelStatsSchema,
  statsOverviewSchema,
  parseAttemptStatusSchema,
  parseAttemptItemSchema,
  apiProcessTelemetrySchema,
  adminTelemetrySchema,
  adminWsChannelSchema,
  adminWsClientMessageSchema,
  adminWsServerMessageSchema,
  phasesUpdatePayloadSchema,
  trackingPhaseIdSchema,
  trackingRebuildStageSchema,
  trackingWatermarkSchema,
  trackingClusterPhaseStatsSchema,
  trackingFieldTrainPhaseStatsSchema,
  trackingJoinPhaseStatsSchema,
  trackingPhaseStatsSchema,
  trackingRebuildStatsSchema,
  trackingRebuildRunSchema,
  parsePipelineJobKindSchema,
  parsePipelineJobStatusSchema,
  parsePipelineStatusResponseSchema,
  parsePipelineStartResponseSchema,
  trackingPipelineConfigSchema,
  trackingPipelineMetricsSchema,
  trackingPhaseManifestEntrySchema,
  trackingStatusResponseSchema,
  pipelineKeySchema,
  workbookPhaseDescriptorSchema,
  workbookRegistryEntrySchema,
  workloadStatusSchema,
  activeWorkloadSchema,
  runOutcomeSchema,
  runHistoryEntrySchema,
  workbookObservabilityResponseSchema,
  runnerDiscoveryResponseSchema,
} from "./admin";
export {
  obsPipelineRuntimeSchema,
  executorKindSchema,
  executorStatusSchema,
  odpRuntimeEntrySchema,
  hostSnapshotSchema,
  executorSnapshotSchema,
  workloadSnapshotSchema,
  triggerCounterKeySchema,
  obsIngestBatchSchema,
  obsIngestMaterializeEntrySchema,
  obsIngestTriggerEntrySchema,
  runtimeObservabilitySnapshotSchema,
  obsTriggerCounterSchema,
  obsMaterializeCounterSchema,
} from "./observability";

export {
  deploymentHostSchema,
  deploymentSpawnSchema,
  schedulingImplSchema,
  deploymentPipelineEntrySchema,
  deploymentRunnersSchema,
  deploymentInfraObsSchema,
  deploymentInfraSchema,
  deploymentTransportKindSchema,
  deploymentTransportRmqSchema,
  deploymentTransportSchema,
  deploymentManifestSchema,
  DEFAULT_DEPLOYMENT_MANIFEST,
} from "../deployment/deploymentManifest.schema.js";

// --- type-only exports ---
export type { HealthResponse, ReadyResponse } from "./health";
export type {
  ChannelManifest,
  ChannelManifestEntry,
  EventLocation,
  EventSubject,
  EventType,
  PvoStats,
  GeoStructure,
  IngestEnvelope,
  LocationPrecision,
  MacroZone,
  ParseConfig,
  ParseCursor,
  ParsedEvent,
  RawMessage,
  RawMessageTelegramExtension,
  Severity,
  IngestAdapterKind,
  ProviderStatus,
  IngestMode,
  SourceKind,
  BindingMode,
  BackfillStrategy,
  BackfillJobStatus,
  CredentialRefs,
  IngestBindingRecord,
  IngestProviderRecord,
  CreateIngestProvider,
  UpdateIngestProvider,
  CreateIngestBinding,
  TelegramAdapterConfig,
  MtproxyTransport,
  ManualIngestRequest,
  ManualIngestResponse,
  TimelineOrderingKey,
  TimelineAnchor,
  TimelineQuery,
  CreateBackfillJob,
  BackfillJobRecord,
  TimelineResponse,
  MessageFeedItem,
  MessageFeedResponse,
  StateChangeEventItem,
  StateChangeEventsResponse,
  IngestManifestEntry,
  IngestManifest,
  SessionKind,
  SessionArtifact,
  SessionDeployRequest,
  SessionProbeResult,
  SessionMaterial,
  SessionWriteInput,
  IngestConnectionPhase,
  IngestProviderConnectionSnapshot,
} from "./ingest";
export type {
  GetActiveEventsQuery,
  GetEventsByRegionQuery,
  GetGeoSyncHistoryQuery,
  GetParseAttemptsQuery,
  GetRegionGeometryQuery,
  SyncAllCommand,
  SyncPlacesCommand,
  SyncRegionsCommand,
} from "./cqrs";
export type {
  DomainEvent,
  DomainEventType,
  PlaceStatusAction,
  PlaceStatusEvent,
} from "./events";
export type {
  AliasDraft,
  GeoEnrichmentArtifact,
  GeoEnrichmentState,
  GeoEnrichmentCatalog,
  GeoEnrichmentDadata,
  GeoEnrichmentFinalizer,
  GeoEnrichmentLlm,
  GeoEnrichmentNominatim,
  GeoEventCategory,
  GeoNode,
  GeoPipelineReport,
  PlaceDraft,
  RegionDraft,
  StatusDictionary,
  StatusDictionaryEntry,
  StateLevel,
  RegionStateRecord,
  RegionStateEvent,
  LayoutTile,
  MapRegionSnapshot,
  MapRegionTraits,
  MapPlaceSnapshot,
  MapVicinityScopeSnapshot,
  PlaceStateEvent,
  MapSnapshot,
  MapRegionsStateResponse,
  MapPlacesStateResponse,
  RegionAdjacency,
  Warning,
  SourceMessage,
} from "./geo";
export type {
  EnrichmentSource,
  MergePrecision,
  ProvenanceMeta,
  FieldProvenance,
  EnricherId,
  PhaseTrigger,
  PhaseTriggerMode,
  PhaseScope,
  PhaseKind,
  EnrichStage,
  PhasePolicy,
  PhaseManifestEntry,
  PhaseManifest,
  PhaseDefinition,
  ManualRunScope,
  PhaseRunStatus,
  PhaseRunControl,
  PhaseRunLogEntry,
  PhaseRunStats,
  PhaseRun,
  PhaseReplayRequest,
  PhaseRunsOverview,
} from "./enrichment";
export type {
  WsChannel,
  WsClientMessage,
  WsServerMessage,
} from "./realtime";
export type {
  AttachRule,
  EventCandidate,
  FinalizeContext,
  FinalizeMode,
  FinalizeResult,
  MessageBlock,
  MessageParseWorkspaceStatus,
  ParseWorkspace,
  TraitAttachment,
} from "./parse";
export type {
  ParseReport,
  ParseReportClassification,
  ParseReportEnrich,
  ParseReportEvent,
  ParseReportGeo,
  ParseReportGeoPipeline,
} from "./reports";
export type {
  BackfillJobProgress,
  BackfillJobListItem,
  BackfillJobsQuery,
  ChannelAdminItem,
  ChannelStats,
  StatsOverview,
  ParseAttemptStatus,
  ParseAttemptItem,
  ApiProcessTelemetry,
  AdminTelemetry,
  AdminWsChannel,
  AdminWsClientMessage,
  AdminWsServerMessage,
  PhasesUpdatePayload,
  ParsePipelineJobKind,
  ParsePipelineJobStatus,
  ParsePipelineStatusResponse,
  ParsePipelineStartResponse,
  TrackingRebuildStage,
  TrackingWatermark,
  TrackingClusterPhaseStats,
  TrackingFieldTrainPhaseStats,
  TrackingJoinPhaseStats,
  TrackingPhaseStats,
  TrackingRebuildStats,
  TrackingRebuildRun,
  TrackingPipelineConfig,
  TrackingPipelineMetrics,
  TrackingPipelineStatus,
  TrackingStatusResponse,
  PipelineKey,
  WorkbookPhaseDescriptorDto,
  WorkbookRegistryEntry,
  WorkloadStatus,
  ActiveWorkload,
  WorkbookRunOutcome,
  RunHistoryEntry,
  WorkbookObservabilityResponse,
  RunnerDiscoveryResponse,
} from "./admin";
export type {
  ObsPipelineRuntime,
  ExecutorKind,
  ExecutorStatus,
  OdpRuntimeEntry,
  HostSnapshot,
  ExecutorSnapshot,
  WorkloadSnapshot,
  TriggerCounterKey,
  ObsIngestBatch,
  ObsIngestMaterializeEntry,
  ObsIngestTriggerEntry,
  RuntimeObservabilitySnapshot,
  ObsTriggerCounter,
  ObsMaterializeCounter,
  ObsWorkloadStatus,
} from "./observability";
export type {
  DeploymentHost,
  DeploymentSpawn,
  SchedulingImpl,
  DeploymentPipelineEntry,
  DeploymentRunners,
  DeploymentInfraObs,
  DeploymentInfra,
  DeploymentTransport,
  DeploymentManifest,
} from "../deployment/deploymentManifest.schema.js";

export {
  EVENT_HEATMAP_FILTER_TYPES,
  EVENT_HEATMAP_TYPE_LABELS,
  eventHeatmapPeriodSchema,
  eventHeatmapMetaSchema,
  eventHeatmapResponseSchema,
  eventHeatmapPeriodMs,
} from "./map/event-heatmap";
export type {
  EventHeatmapFilterType,
  EventHeatmapPeriod,
  EventHeatmapMeta,
  EventHeatmapResponse,
} from "./map/event-heatmap";

export {
  nodeModeSchema,
  trackStatusSchema,
  threatProfileSchema,
  sourceRefSchema,
  trajectoryNodeSchema,
  trajectoryTrackSchema,
  tracksListQuerySchema,
  tracksListResponseSchema,
} from "./map/tracks";
export type {
  NodeMode,
  TrackStatus,
  ThreatProfile,
  TrajectoryNode,
  TrajectoryTrack,
  TracksListQuery,
  TracksListResponse,
} from "./map/tracks";

export {
  tracksFlowQuerySchema,
  tracksFlowResponseSchema,
} from "./map/tracks-flow";
export type {
  TracksFlowQuery,
  TracksFlowResponse,
} from "./map/tracks-flow";

export {
  tracksGravityQuerySchema,
  tracksGravityResponseSchema,
} from "./map/tracks-gravity";
export type {
  TracksGravityQuery,
  TracksGravityResponse,
} from "./map/tracks-gravity";

export {
  geoBasemapManifestSchema,
} from "./geo/geo-basemap-manifest";
export type { GeoBasemapManifest } from "./geo/geo-basemap-manifest";

/** Браузер-безопасные хелперы карты (Vite: @radar/shared → этот barrel, не src/index). */
export { isPlaceSuppressedByRegionClear } from "../domain/region-state/statusEventOrdering.js";
export type { MapStatusAction } from "../domain/region-state/statusEventOrdering.js";
export {
  buildBackfillJobProgress,
  computeBackfillPercentApprox,
  mergeBackfillPercentMonotonic,
  pickFurtherCheckpointOffsetId,
  readBackfillPreflight,
} from "../domain/ingest/backfillProgress.js";

