// --- runtime exports (schemas, functions, classes) ---
export { healthResponseSchema, readyResponseSchema } from "./health";
export {
  processMetricsSchema,
  workerProbeStatusSchema,
  workerStatusResponseSchema,
} from "./worker-status";
export type {
  ProcessMetrics,
  WorkerProbeStatus,
  WorkerStatusResponse,
} from "./worker-status";
export {
  channelManifestEntrySchema,
  channelManifestSchema,
  eventLocationSchema,
  eventSubjectSchema,
  eventTypeSchema,
  pvoStatsSchema,
  geoStructureSchema,
  ingestEnvelopeSchema,
  locationPrecisionSchema,
  macroZoneSchema,
  parseConfigSchema,
  parseCursorSchema,
  parsedEventSchema,
  rawMessageSchema,
  rawMessageTelegramExtensionSchema,
  severitySchema,
  ingestAdapterKindSchema,
  providerStatusSchema,
  ingestModeSchema,
  sourceKindSchema,
  bindingModeSchema,
  backfillStrategySchema,
  backfillJobStatusSchema,
  credentialRefsSchema,
  adapterConfigSchema,
  ingestBindingRecordSchema,
  ingestProviderRecordSchema,
  createIngestProviderSchema,
  updateIngestProviderSchema,
  createIngestBindingSchema,
  telegramAdapterConfigSchema,
  mtproxyTransportSchema,
  manualIngestRequestSchema,
  manualIngestResponseSchema,
  timelineOrderingKeySchema,
  timelineAnchorSchema,
  timelineQuerySchema,
  createBackfillJobSchema,
  backfillJobRecordSchema,
  timelineResponseSchema,
  fetchHistoryBatchSchema,
  messageFeedItemSchema,
  messageFeedResponseSchema,
  stateChangeEventItemSchema,
  stateChangeEventsResponseSchema,
  ingestManifestEntrySchema,
  ingestManifestSchema,
  sessionKindSchema,
  sessionArtifactSchema,
  sessionDeployRequestSchema,
  sessionProbeResultSchema,
} from "./ingest";
export {
  getActiveEventsQuerySchema,
  getEventsByRegionQuerySchema,
  getGeoSyncHistoryQuerySchema,
  getParseAttemptsQuerySchema,
  getRegionGeometryQuerySchema,
  syncAllCommandSchema,
  syncPlacesCommandSchema,
  syncRegionsCommandSchema,
} from "./cqrs";
export { domainEventSchema, domainEventTypeSchema } from "./events";
export {
  placeStatusActionSchema,
  placeStatusEventSchema,
} from "./events";
export {
  aliasDraftSchema,
  geoEnrichmentArtifactSchema,
  geoEnrichmentStateSchema,
  geoEnrichmentCatalogSchema,
  geoEnrichmentDadataSchema,
  geoEnrichmentFinalizerSchema,
  geoEnrichmentLlmSchema,
  geoEnrichmentNominatimSchema,
  geoEventCategorySchema,
  geoPipelineReportSchema,
  geoPipelineStepLogSchema,
  placeDraftSchema,
  regionDraftSchema,
  statusDictionaryEntrySchema,
  statusDictionarySchema,
  stateLevelSchema,
  STATE_LEVEL_RANK,
  regionStateRecordSchema,
  regionStateEventSchema,
  layoutTileSchema,
  mapRegionSnapshotSchema,
  mapPlaceSnapshotSchema,
  placeStateEventSchema,
  mapSnapshotSchema,
  regionAdjacencySchema,
  warningSchema,
  sourceMessageSchema,
  sourceMessageResponseSchema,
} from "./geo";
export {
  enrichmentSourceSchema,
  mergePrecisionSchema,
  provenanceMetaSchema,
  fieldProvenance,
  SOURCE_TRUST,
  PRECISION_RANK,
  enricherIdSchema,
  phaseTriggerSchema,
  phaseScopeSchema,
  phaseKindSchema,
  enrichStageSchema,
  phasePolicySchema,
  DEFAULT_PHASE_POLICY,
  phaseManifestEntrySchema,
  phaseManifestSchema,
  phaseDefinitionSchema,
  manualRunScopeSchema,
  LEGACY_PHASE_ID_MAP,
  normalizePhaseManifestEntry,
  phaseRunStatusSchema,
  phaseRunControlSchema,
  phaseRunLogEntrySchema,
  phaseRunStatsSchema,
  phaseRunSchema,
  phaseReplayRequestSchema,
  phaseRunsOverviewSchema,
} from "./enrichment";
export {
  wsChannelSchema,
  wsClientMessageSchema,
  wsServerMessageSchema,
} from "./realtime";
export {
  parseReportClassificationSchema,
  parseReportEnrichSchema,
  parseReportEventSchema,
  parseReportGeoSchema,
  parseReportSchema,
} from "./reports";
export {
  backfillJobProgressSchema,
  backfillJobListItemSchema,
  backfillJobsQuerySchema,
  channelAdminItemSchema,
  channelStatsSchema,
  statsOverviewSchema,
  parseAttemptStatusSchema,
  parseAttemptItemSchema,
  apiProcessTelemetrySchema,
  adminTelemetrySchema,
  adminWsChannelSchema,
  adminWsClientMessageSchema,
  adminWsServerMessageSchema,
  phasesUpdatePayloadSchema,
} from "./admin";

// --- type-only exports ---
export type { HealthResponse, ReadyResponse } from "./health";
export type {
  ChannelManifest,
  ChannelManifestEntry,
  EventLocation,
  EventSubject,
  EventType,
  PvoStats,
  GeoStructure,
  IngestEnvelope,
  LocationPrecision,
  MacroZone,
  ParseConfig,
  ParseCursor,
  ParsedEvent,
  RawMessage,
  RawMessageTelegramExtension,
  Severity,
  IngestAdapterKind,
  ProviderStatus,
  IngestMode,
  SourceKind,
  BindingMode,
  BackfillStrategy,
  BackfillJobStatus,
  CredentialRefs,
  IngestBindingRecord,
  IngestProviderRecord,
  CreateIngestProvider,
  UpdateIngestProvider,
  CreateIngestBinding,
  TelegramAdapterConfig,
  MtproxyTransport,
  ManualIngestRequest,
  ManualIngestResponse,
  TimelineOrderingKey,
  TimelineAnchor,
  TimelineQuery,
  CreateBackfillJob,
  BackfillJobRecord,
  TimelineResponse,
  MessageFeedItem,
  MessageFeedResponse,
  StateChangeEventItem,
  StateChangeEventsResponse,
  IngestManifestEntry,
  IngestManifest,
  SessionKind,
  SessionArtifact,
  SessionDeployRequest,
  SessionProbeResult,
  SessionMaterial,
  SessionWriteInput,
} from "./ingest";
export type {
  GetActiveEventsQuery,
  GetEventsByRegionQuery,
  GetGeoSyncHistoryQuery,
  GetParseAttemptsQuery,
  GetRegionGeometryQuery,
  SyncAllCommand,
  SyncPlacesCommand,
  SyncRegionsCommand,
} from "./cqrs";
export type {
  DomainEvent,
  DomainEventType,
  PlaceStatusAction,
  PlaceStatusEvent,
} from "./events";
export type {
  AliasDraft,
  GeoEnrichmentArtifact,
  GeoEnrichmentState,
  GeoEnrichmentCatalog,
  GeoEnrichmentDadata,
  GeoEnrichmentFinalizer,
  GeoEnrichmentLlm,
  GeoEnrichmentNominatim,
  GeoEventCategory,
  GeoNode,
  GeoPipelineReport,
  PlaceDraft,
  RegionDraft,
  StatusDictionary,
  StatusDictionaryEntry,
  StateLevel,
  RegionStateRecord,
  RegionStateEvent,
  LayoutTile,
  MapRegionSnapshot,
  MapPlaceSnapshot,
  PlaceStateEvent,
  MapSnapshot,
  RegionAdjacency,
  Warning,
  SourceMessage,
} from "./geo";
export type {
  EnrichmentSource,
  MergePrecision,
  ProvenanceMeta,
  FieldProvenance,
  EnricherId,
  PhaseTrigger,
  PhaseScope,
  PhaseKind,
  EnrichStage,
  PhasePolicy,
  PhaseManifestEntry,
  PhaseManifest,
  PhaseDefinition,
  ManualRunScope,
  PhaseRunStatus,
  PhaseRunControl,
  PhaseRunLogEntry,
  PhaseRunStats,
  PhaseRun,
  PhaseReplayRequest,
  PhaseRunsOverview,
} from "./enrichment";
export type {
  WsChannel,
  WsClientMessage,
  WsServerMessage,
} from "./realtime";
export type {
  ParseReport,
  ParseReportClassification,
  ParseReportEnrich,
  ParseReportEvent,
  ParseReportGeo,
  ParseReportGeoPipeline,
} from "./reports";
export type {
  BackfillJobProgress,
  BackfillJobListItem,
  BackfillJobsQuery,
  ChannelAdminItem,
  ChannelStats,
  StatsOverview,
  ParseAttemptStatus,
  ParseAttemptItem,
  ApiProcessTelemetry,
  AdminTelemetry,
  AdminWsChannel,
  AdminWsClientMessage,
  AdminWsServerMessage,
  PhasesUpdatePayload,
} from "./admin";

/** Браузер-безопасные хелперы карты (Vite: @radar/shared → этот barrel, не src/index). */
export { isPlaceSuppressedByRegionClear } from "../domain/region-state/statusEventOrdering.js";
export type { MapStatusAction } from "../domain/region-state/statusEventOrdering.js";

