// --- runtime exports (schemas, functions, classes) ---
export {
  aliasDraftSchema,
  channelManifestEntrySchema,
  channelManifestSchema,
  domainEventSchema,
  domainEventTypeSchema,
  eventLocationSchema,
  eventTypeSchema,
  geoStructureSchema,
  getActiveEventsQuerySchema,
  getEventsByRegionQuerySchema,
  getGeoSyncHistoryQuerySchema,
  getParseAttemptsQuerySchema,
  getRegionGeometryQuerySchema,
  healthResponseSchema,
  ingestEnvelopeSchema,
  locationPrecisionSchema,
  macroZoneSchema,
  parseConfigSchema,
  parseCursorSchema,
  parsedEventSchema,
  placeDraftSchema,
  rawMessageSchema,
  readyResponseSchema,
  regionDraftSchema,
  severitySchema,
  syncAllCommandSchema,
  syncPlacesCommandSchema,
  syncRegionsCommandSchema,
} from "./schemas";
export { InProcessEventBus } from "./events/inProcessEventBus";

// --- type-only exports ---
export type {
  AliasDraft,
  ChannelManifest,
  ChannelManifestEntry,
  DomainEvent,
  DomainEventType,
  EventLocation,
  EventType,
  GetActiveEventsQuery,
  GetEventsByRegionQuery,
  GeoStructure,
  GetGeoSyncHistoryQuery,
  GetParseAttemptsQuery,
  GetRegionGeometryQuery,
  HealthResponse,
  IngestEnvelope,
  LocationPrecision,
  MacroZone,
  ParseConfig,
  ParseCursor,
  ParsedEvent,
  PlaceDraft,
  RawMessage,
  ReadyResponse,
  RegionDraft,
  Severity,
  SyncAllCommand,
  SyncPlacesCommand,
  SyncRegionsCommand,
} from "./schemas";
export type {
  EventHandler,
  IEventPublisher,
  IEventSubscriber,
  GeoProviderSnapshot,
  IGeoSourceProvider,
  ILocationEnricher,
  LocationCandidate,
  IEventClassifier,
  ClassifiedPost,
  IDomainEventRepository,
  IEventLocationRepository,
  IIngestCursorRepository,
  IParsedEventRepository,
  IPlaceAliasRepository,
  IPlaceCacheRepository,
  IPlaceRepository,
  IRawMessageRepository,
  IRegionRepository,
  ISyncAuditRepository,
  PlaceAliasRecord,
  PlaceRecord,
  RegionRecord,
  Unsubscribe,
} from "./ports";
