// --- runtime exports (schemas, functions, classes) ---
export {
  aliasDraftSchema,
  channelManifestEntrySchema,
  channelManifestSchema,
  domainEventSchema,
  domainEventTypeSchema,
  eventLocationSchema,
  eventSubjectSchema,
  eventTypeSchema,
  pvoStatsSchema,
  geoEnrichmentArtifactSchema,
  geoEnrichmentStateSchema,
  geoEnrichmentCatalogSchema,
  geoEnrichmentDadataSchema,
  geoEnrichmentFinalizerSchema,
  geoEnrichmentLlmSchema,
  geoEnrichmentNominatimSchema,
  geoBasemapManifestSchema,
  geoEventCategorySchema,
  geoPipelineReportSchema,
  geoStructureSchema,
  getActiveEventsQuerySchema,
  getEventsByRegionQuerySchema,
  getGeoSyncHistoryQuerySchema,
  getParseAttemptsQuerySchema,
  getRegionGeometryQuerySchema,
  healthResponseSchema,
  ingestEnvelopeSchema,
  locationPrecisionSchema,
  macroZoneSchema,
  parseConfigSchema,
  parseCursorSchema,
  parsedEventSchema,
  placeStatusActionSchema,
  placeStatusEventSchema,
  placeDraftSchema,
  rawMessageSchema,
  rawMessageTelegramExtensionSchema,
  readyResponseSchema,
  processMetricsSchema,
  workerProbeStatusSchema,
  workerStatusResponseSchema,
  backfillJobProgressSchema,
  backfillJobListItemSchema,
  backfillJobsQuerySchema,
  channelAdminItemSchema,
  channelStatsSchema,
  statsOverviewSchema,
  parseAttemptStatusSchema,
  parseAttemptItemSchema,
  apiProcessTelemetrySchema,
  adminTelemetrySchema,
  adminWsChannelSchema,
  adminWsClientMessageSchema,
  adminWsServerMessageSchema,
  phasesUpdatePayloadSchema,
  trackingRebuildStageSchema,
  trackingWatermarkSchema,
  trackingRebuildStatsSchema,
  trackingRebuildRunSchema,
  parsePipelineStatusResponseSchema,
  parsePipelineStartResponseSchema,
  trackingTuneRunSchema,
  trackingTuneRunStatusSchema,
  trackingTuneStartRequestSchema,
  trackingPipelineConfigSchema,
  trackingPipelineMetricsSchema,
  trackingStatusResponseSchema,
  regionDraftSchema,
  severitySchema,
  syncAllCommandSchema,
  syncPlacesCommandSchema,
  syncRegionsCommandSchema,
  statusDictionaryEntrySchema,
  statusDictionarySchema,
  stateLevelSchema,
  STATE_LEVEL_RANK,
  regionStateRecordSchema,
  regionStateEventSchema,
  layoutTileSchema,
  mapRegionSnapshotSchema,
  mapPlaceSnapshotSchema,
  placeStateEventSchema,
  mapSnapshotSchema,
  mapRegionsStateResponseSchema,
  mapPlacesStateResponseSchema,
  regionAdjacencySchema,
  warningSchema,
  sourceMessageSchema,
  sourceMessageResponseSchema,
  wsChannelSchema,
  wsClientMessageSchema,
  wsServerMessageSchema,
  parseReportClassificationSchema,
  parseReportEnrichSchema,
  parseReportEventSchema,
  parseReportGeoSchema,
  parseReportSchema,
  attachRuleSchema,
  parseWorkspaceSchema,
  finalizeContextSchema,
  finalizeResultSchema,
  messageParseWorkspaceStatusSchema,
  ingestAdapterKindSchema,
  providerStatusSchema,
  ingestModeSchema,
  sourceKindSchema,
  bindingModeSchema,
  backfillStrategySchema,
  backfillJobStatusSchema,
  credentialRefsSchema,
  adapterConfigSchema,
  ingestBindingRecordSchema,
  ingestProviderRecordSchema,
  createIngestProviderSchema,
  updateIngestProviderSchema,
  createIngestBindingSchema,
  telegramAdapterConfigSchema,
  mtproxyTransportSchema,
  manualIngestRequestSchema,
  manualIngestResponseSchema,
  timelineOrderingKeySchema,
  timelineAnchorSchema,
  timelineQuerySchema,
  createBackfillJobSchema,
  backfillJobRecordSchema,
  timelineResponseSchema,
  fetchHistoryBatchSchema,
  messageFeedItemSchema,
  messageFeedResponseSchema,
  stateChangeEventItemSchema,
  stateChangeEventsResponseSchema,
  EVENT_HEATMAP_FILTER_TYPES,
  EVENT_HEATMAP_TYPE_LABELS,
  eventHeatmapPeriodSchema,
  eventHeatmapMetaSchema,
  eventHeatmapResponseSchema,
  eventHeatmapPeriodMs,
  nodeModeSchema,
  trackStatusSchema,
  threatProfileSchema,
  sourceRefSchema,
  trajectoryNodeSchema,
  trajectoryTrackSchema,
  tracksListQuerySchema,
  tracksListResponseSchema,
  tracksFlowQuerySchema,
  tracksFlowResponseSchema,
  ingestManifestEntrySchema,
  ingestManifestSchema,
  sessionKindSchema,
  sessionArtifactSchema,
  sessionDeployRequestSchema,
  sessionProbeResultSchema,
  enrichmentSourceSchema,
  mergePrecisionSchema,
  provenanceMetaSchema,
  fieldProvenance,
  SOURCE_TRUST,
  PRECISION_RANK,
  enricherIdSchema,
  phaseTriggerSchema,
  phaseScopeSchema,
  phaseKindSchema,
  enrichStageSchema,
  phasePolicySchema,
  DEFAULT_PHASE_POLICY,
  phaseManifestEntrySchema,
  phaseManifestSchema,
  phaseDefinitionSchema,
  manualRunScopeSchema,
  normalizePhaseManifestEntry,
  LEGACY_PHASE_ID_MAP,
  phaseRunStatusSchema,
  phaseRunControlSchema,
  phaseRunLogEntrySchema,
  phaseRunStatsSchema,
  phaseRunSchema,
  phaseReplayRequestSchema,
} from "./schemas";
export {
  buildTrackEdges,
  rollupSegmentCounts,
  filterEdgesByAsOf,
  filterNodesByAsOf,
  buildSegmentKey,
  PROFILE_KINEMATICS,
  resolveProfileKinematics,
  maxEpsilonTemporalMs,
  TRACKING_PIPELINE_TYPES,
  trackingPipelineTypesSqlIn,
  TRACKING_TARGET_EVENT_TYPES,
  trackingTargetEventTypesSqlIn,
  resolveThreatProfile,
  resolveNodeMode,
  observationCovarianceMeters,
  scaleObservationCovariance,
  haversineDistanceM,
  isDistinctDuplicate,
  innovationGate,
  kalmanStep,
  kalmanInitState,
  buildTrackMetadata,
  scoreSeedCandidate,
  isNearAnyOpenTrack,
  checkTrackTermination,
  terminateByIntercept,
  stdbscanDedup,
  canEnterAttention,
  canEnterPipeline,
  resolveAssignments,
  computeSeedScore,
  computeFrontProximityCoeff,
  DEFAULT_SEED_MIN,
  computeTrackingFitness,
  patternSearchStep,
  defaultTuneAxes,
  probeCenter,
  tuneCenterFromProfile,
  tuneCenterToProfilePatch,
} from "./domain/tracking";
export { InProcessEventBus } from "./events/inProcessEventBus";
export { mergePlaceContribution, monotonicTrustState } from "./ports/placeContributionMerge";
export { mergeContribution } from "./domain/mergeContribution";
export type { ProvenanceAccumulator } from "./domain/mergeContribution";
export {
  isStaleStatusEvent,
  isMapEventOlderThanTtl,
  isPlaceSuppressedByRegionClear,
  PLACE_STATUS_EVENT_AT_META_KEY,
  readPlaceStatusEventAt,
} from "./domain/region-state/statusEventOrdering";
export type { MapStatusAction } from "./domain/region-state/statusEventOrdering";
export {
  DEFAULT_MAP_STATE_TTL_MS,
  REGION_CALM_SUPPRESS_MS,
  resolveMapStateTtlMs,
} from "./domain/region-state/mapStateTtl";
export {
  foldMapState,
  foldRegionMapState,
  foldPlaceMapState,
  foldVicinityScopeMapState,
  filterRegionScopedFacts,
  shouldIncomingBeatWinner,
  isRegionVisibleInSnapshot,
} from "./domain/region-state/mapStateFold";
export type {
  EventLocationFact,
  MapEntityWinner,
  MapStateFoldInput,
  MapStateFoldResult,
  FoldPlaceMapStateInput,
  FoldVicinityScopeMapStateInput,
  VicinityScopeWinner,
} from "./domain/region-state/mapStateFold";
export {
  CRITICAL_WINDOW_MS,
  THREAT_MAP_STATUS_CODES,
  isCriticalTopBarThreat,
  isThreatMapStatusCode,
  isWithinCriticalWindow,
  resolveThreatVisual,
  resolveThreatVisualKey,
  shouldShowRegionThreatMarker,
} from "./visual/threat-visual";
export type {
  ResolveThreatVisualInput,
  ThreatTraits,
  ThreatVisual,
  ThreatVisualKey,
  ThreatMapStatusCode,
} from "./visual/threat-visual";
export {
  isMassClearTextEligible,
  normalizeClearHaystack,
  resolveMassClearTargets,
} from "./domain/region-state/massClearTargets";
export type { MassClearRegionRef } from "./domain/region-state/massClearTargets";
export {
  buildAuthorPlaceClearFacts,
  loadMapFacts,
  loadRegionMapFacts,
  loadPlaceMapFacts,
  loadVicinityMapFacts,
  loadMapFoldFacts,
} from "./domain/region-state/mapFactsLoader";
export { isPgDeadlockError, isPgContendedReadError, isPgStatementTimeoutError, withPgContendedReadRetry, withPgDeadlockRetry } from "./infrastructure/pgDeadlockRetry";
export type { MapFactsDbQuery, MapFoldDbQuery } from "./domain/region-state/mapFactsLoader";
export {
  buildCandidateId,
  buildCandidateMergeKey,
} from "./domain/parse/candidateKeys";
export {
  migrateParseWorkspaceV1ToV2,
  normalizeParseWorkspace,
} from "./domain/parse/workspaceMigrate";
export { ingestMessageHash } from "./domain/ingestMessageHash";
export type { RawMessageHashInput } from "./domain/ingestMessageHash";
export {
  readBackfillPreflight,
  readBackfillStreamReverse,
  resolveBackfillIdBounds,
  computeBackfillPercentApprox,
  mergeBackfillPercentMonotonic,
  pickFurtherCheckpointOffsetId,
  buildBackfillJobProgress,
  readBackfillRoundRobinSlice,
  withBackfillRoundRobinSlice,
  resolveBackfillRoundRobinSlice,
  BACKFILL_ROUND_ROBIN_SLICE_KEY,
} from "./domain/ingest/backfillProgress";
export type {
  BackfillPreflight,
  BackfillProgressInput,
  BackfillRoundRobinSlice,
} from "./domain/ingest/backfillProgress";
export {
  canonicalRegionCode,
  parseKladrSubjectPrefix,
} from "./domain/regionLookupCode";
export {
  collectPlaceMatchStems,
  normalizePlaceMatchLabel,
  placeStem,
  placeStemCore,
} from "./domain/geo/placeStem";
export {
  GEO_ENRICH_ELIGIBLE_KINDS,
  GEO_ENRICH_MIN_KIND,
  isGeoEnrichEligibleKind,
  kindMeetsFloor,
  placeKindRank,
  sortPlaceScanEntriesStable,
} from "./domain/geo/placeKindRank";
export type {
  FindByStemGlobalOptions,
  GeoSpanToken,
  IPlaceScanPort,
  PlaceKindHint,
  PlaceResolveContext,
  PlaceScanEntry,
  PlaceScanHit,
  TextSpan,
} from "./ports/place-scan";
export {
  normalizePlaceIdentityName,
  placeIdentityMatches,
  resolvePlaceIdentityKey,
} from "./domain/geo/placeIdentity";
export type { PlaceIdentityInput } from "./domain/geo/placeIdentity";
export {
  buildCatalogPlaceGeocodeQuery,
  buildRegionScopedGeocodeQuery,
  formatFederalSubjectLabel,
  isFederalSubjectLabel,
  normalizeFederalSubjectDisplay,
  parseRegionViewbox,
  resolveGeocodeCountryLabel,
  resolveNominatimCountryCode,
} from "./domain/geo/catalogPlaceGeocodeQuery";
export type { CatalogPlaceGeocodeInput, NominatimViewbox } from "./domain/geo/catalogPlaceGeocodeQuery";
export { normalizeRegionCodeAlias } from "./domain/regionCodeAlias";
export { layoutTileToCentroid } from "./domain/layoutCentroid";
export { maxStateLevel } from "./domain/maxStateLevel";
export { classifyContentKind, type ContentKind } from "./domain/parsing/classifyContentKind";
export { extractUncertainFlag } from "./domain/parsing/extractUncertainFlag";
export { extractMultipleFixationFlag } from "./domain/parsing/extractMultipleFixationFlag";
export { extractNegativeMonitoringFlag } from "./domain/parsing/extractNegativeMonitoringFlag";
export { extractMassFlag } from "./domain/parsing/extractMassFlag";
export { groomRawTextForDisplay } from "./domain/parsing/groomRawTextForDisplay";
export {
  GEO_PHRASE_STOPWORDS,
  isGeoPhraseStopword,
} from "./domain/parsing/geoPhraseStopwords";
export {
  resolveRawMessagePostedAtOrder,
  type RawMessagePostedAtOrder,
} from "./domain/phases/phaseClaimOrder";
export { resolveGeoEnrichmentProvider } from "./domain/phases/phaseGeoProvider";
export { phaseRunsOverviewSchema, type PhaseRunsOverview } from "./schemas/enrichment/phase-admin";
export { SourceUniquenessRegistry } from "./ports/source-uniqueness";
export type {
  EventEvidenceRecord,
  IEventEvidenceRepository,
  IPlaceEnrichmentJobRepository,
  PlaceEnrichmentJobRecord,
  PlaceEnrichmentProvider,
} from "./ports/repositories";

// --- type-only exports ---
export type {
  AliasDraft,
  ChannelManifest,
  ChannelManifestEntry,
  DomainEvent,
  DomainEventType,
  EventLocation,
  EventSubject,
  EventType,
  PvoStats,
  GeoEnrichmentArtifact,
  GeoEnrichmentState,
  GeoEnrichmentCatalog,
  GeoEnrichmentDadata,
  GeoEnrichmentFinalizer,
  GeoEnrichmentLlm,
  GeoEnrichmentNominatim,
  GeoBasemapManifest,
  GeoEventCategory,
  GeoNode,
  GeoPipelineReport,
  GetActiveEventsQuery,
  GetEventsByRegionQuery,
  GeoStructure,
  GetGeoSyncHistoryQuery,
  GetParseAttemptsQuery,
  GetRegionGeometryQuery,
  HealthResponse,
  IngestEnvelope,
  LocationPrecision,
  MacroZone,
  PlaceStatusAction,
  PlaceStatusEvent,
  ParseConfig,
  ParseCursor,
  ParsedEvent,
  PlaceDraft,
  RawMessage,
  RawMessageTelegramExtension,
  ReadyResponse,
  ProcessMetrics,
  WorkerProbeStatus,
  WorkerStatusResponse,
  BackfillJobProgress,
  BackfillJobListItem,
  BackfillJobsQuery,
  ChannelAdminItem,
  ChannelStats,
  StatsOverview,
  ParseAttemptStatus,
  ParseAttemptItem,
  ApiProcessTelemetry,
  AdminTelemetry,
  AdminWsChannel,
  AdminWsClientMessage,
  AdminWsServerMessage,
  PhasesUpdatePayload,
  ParsePipelineJobKind,
  ParsePipelineJobStatus,
  ParsePipelineStatusResponse,
  ParsePipelineStartResponse,
  TrackingTuneRun,
  TrackingTuneStartRequest,
  TrackingRebuildStage,
  TrackingWatermark,
  TrackingRebuildStats,
  TrackingRebuildRun,
  TrackingPipelineConfig,
  TrackingPipelineMetrics,
  TrackingStatusResponse,
  RegionDraft,
  Severity,
  SyncAllCommand,
  SyncPlacesCommand,
  SyncRegionsCommand,
  StatusDictionary,
  StatusDictionaryEntry,
  StateLevel,
  RegionStateRecord,
  RegionStateEvent,
  LayoutTile,
  MapRegionSnapshot,
  MapRegionTraits,
  MapPlaceSnapshot,
  MapVicinityScopeSnapshot,
  PlaceStateEvent,
  MapSnapshot,
  MapRegionsStateResponse,
  MapPlacesStateResponse,
  RegionAdjacency,
  Warning,
  SourceMessage,
  WsChannel,
  WsClientMessage,
  WsServerMessage,
  ParseReport,
  ParseReportClassification,
  ParseReportEnrich,
  ParseReportEvent,
  ParseReportGeo,
  ParseReportGeoPipeline,
  AttachRule,
  EventCandidate,
  FinalizeContext,
  FinalizeMode,
  FinalizeResult,
  MessageBlock,
  MessageParseWorkspaceStatus,
  ParseWorkspace,
  TraitAttachment,
  IngestAdapterKind,
  ProviderStatus,
  IngestMode,
  SourceKind,
  BindingMode,
  BackfillStrategy,
  BackfillJobStatus,
  CredentialRefs,
  IngestBindingRecord,
  IngestProviderRecord,
  CreateIngestProvider,
  UpdateIngestProvider,
  CreateIngestBinding,
  TelegramAdapterConfig,
  MtproxyTransport,
  ManualIngestRequest,
  ManualIngestResponse,
  TimelineOrderingKey,
  TimelineAnchor,
  TimelineQuery,
  CreateBackfillJob,
  BackfillJobRecord,
  TimelineResponse,
  MessageFeedItem,
  MessageFeedResponse,
  StateChangeEventItem,
  StateChangeEventsResponse,
  EventHeatmapFilterType,
  EventHeatmapPeriod,
  EventHeatmapMeta,
  EventHeatmapResponse,
  NodeMode,
  TrackStatus,
  ThreatProfile,
  TrajectoryNode,
  TrajectoryTrack,
  TracksListQuery,
  TracksListResponse,
  TracksFlowQuery,
  TracksFlowResponse,
  IngestManifestEntry,
  IngestManifest,
  SessionKind,
  SessionArtifact,
  SessionDeployRequest,
  SessionProbeResult,
  SessionMaterial,
  SessionWriteInput,
  EnrichmentSource,
  MergePrecision,
  ProvenanceMeta,
  FieldProvenance,
  EnricherId,
  PhaseTrigger,
  PhaseScope,
  PhaseKind,
  EnrichStage,
  PhasePolicy,
  PhaseManifestEntry,
  PhaseManifest,
  PhaseDefinition,
  ManualRunScope,
  PhaseRun,
  PhaseRunStatus,
  PhaseRunControl,
  PhaseRunLogEntry,
  PhaseRunStats,
  PhaseReplayRequest,
} from "./schemas";
export type {
  ProfileKinematics,
  TrackingCandidate,
  KalmanStateJson,
  SourceRef,
  ObservationCovariance,
  GateResult,
  OpenTrackSummary,
  TerminationReason,
  StdbscanDedupResult,
  TrajectoryEdge,
  SegmentRollup,
  TrackingDomainNode,
  TrackingDomainTrack,
  MutationState,
  TrackAttentionTarget,
  AssignStats,
  AssignDecision,
  TuneCenter,
} from "./domain/tracking";
export type {
  EventHandler,
  IEventPublisher,
  IEventSubscriber,
  GeoProviderSnapshot,
  IGeoSourceProvider,
  ILocationEnricher,
  LocationCandidate,
  LocationEnrichInput,
  IEventClassifier,
  ClassifiedPost,
  ISourceUniquenessContributor,
  IngestNormalizedMessage,
  IngestAdapterHealth,
  IngestAdapterContext,
  IngestMessageSink,
  IRawIngestAdapter,
  StreamHistoryParams,
  ChannelHistoryBounds,
  TelegramMtprotoAppCredentials,
  ISessionRuntimeStore,
  ISessionBootstrapService,
  ILlmChatClient,
  LlmChatMessage,
  LlmChatOptions,
  LlmChatResult,
  LlmChatRole,
  IDomainEventRepository,
  IDomainEventOutbox,
  IEventLocationRepository,
  IIngestCursorRepository,
  IIngestProviderRepository,
  IIngestBindingRepository,
  IIngestBackfillJobRepository,
  BackfillJobFilter,
  IParseAttemptRepository,
  ParseAttemptInput,
  IRawMessageTelegramExtensionRepository,
  IChannelRepository,
  IParsedEventRepository,
  ParsedEventRecord,
  IMessageParseWorkspaceRepository,
  MessageParseWorkspaceRecord,
  IPlaceAliasRepository,
  IPlaceCacheRepository,
  IPlaceRepository,
  IRawMessageRepository,
  IRegionRepository,
  IStatusDictionaryRepository,
  ISyncAuditRepository,
  IEnrichmentQueueRepository,
  IPhaseCoverageRepository,
  PhaseCoverageTask,
  PhaseCoverageStatus,
  EnrichmentTask,
  EnrichmentTaskStatus,
  IPhaseDefinitionRepository,
  PhaseDefinitionRecord,
  IPhaseRunRepository,
  PhaseRunFilter,
  ChannelRecord,
  PlaceAliasRecord,
  PlaceCacheHit,
  PlaceCacheProvider,
  PlaceCachePutMeta,
  PlaceContribution,
  PlaceProvider,
  PlaceRecord,
  RegionRecord,
  StatusDictionaryRecord,
  Unsubscribe,
} from "./ports";

export {
  createProgress,
  createStageProgressReporter,
  type CreateProgressOptions,
  type ProgressCounters,
  type ProgressHandle,
  type StageProgressHandle,
  type StageProgressReporter,
} from "./cli/progress";

